module SkelLI where

-- Haskell module generated by the BNF converter

import AbsLI
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Prog declarations -> failure x
transDeclaration :: Declaration -> Result
transDeclaration x = case x of
  DecF function -> failure x
  DecGV assigment -> failure x
transFunction :: Function -> Result
transFunction x = case x of
  Fun ident idents stms -> failure x
transAssigment :: Assigment -> Result
transAssigment x = case x of
  SAsss ident exp -> failure x
transStm :: Stm -> Result
transStm x = case x of
  SAss assigment -> failure x
  SBlock stms -> failure x
  SWhile exp stm -> failure x
  SReturn exp -> failure x
  SIf exp stm1 stm2 -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EOr exp1 exp2 -> failure x
  EAnd exp1 exp2 -> failure x
  ENot exp -> failure x
  ECon exp1 exp2 -> failure x
  EAdd exp1 exp2 -> failure x
  ESub exp1 exp2 -> failure x
  EMul exp1 exp2 -> failure x
  EDiv exp1 exp2 -> failure x
  Call ident exps -> failure x
  EInt integer -> failure x
  EVar ident -> failure x
  EStr string -> failure x
  ETrue -> failure x
  EFalse -> failure x

